name: deploy

on:
  workflow_run:
    workflows: ["build and test"]
    types:
      - completed

jobs:
  deploy:
    # Only run this in case building and testing succeeded and the event is a push to master
    if: "${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/master' }}"
    runs-on: ubuntu-latest
    steps:
    - name: Push to dokku
      uses: dokku/github-action@v1.0.1
      with:
        git_remote_url: 'ssh://dokku@vps.fdlo.ch:22/cassette'
        ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}